"""Repository contract for profile-scoped chunk embedding persistence."""

from dataclasses import dataclass
from typing import Protocol
from uuid import UUID


@dataclass(frozen=True, slots=True)
class ChunkEmbedding:
    """One validated vector associated with one chunk."""

    chunk_id: UUID
    values: tuple[float, ...]


@dataclass(frozen=True, slots=True)
class CreateChunkEmbeddings:
    """An idempotent batch of vectors generated by one immutable profile."""

    embedding_profile_id: UUID
    embeddings: tuple[ChunkEmbedding, ...]


class ChunkEmbeddingRepository(Protocol):
    """Persist vectors without allowing a profile identity to be inferred."""

    async def create_many(self, command: CreateChunkEmbeddings) -> None:
        """Store missing vectors and preserve existing retry outputs unchanged."""
